package com.agentic.shortener.orchestration.audit;

public enum AuditEventType {

    WORKFLOW_CREATED,
    WORKFLOW_STARTED,

    TASK_STARTED,
    TASK_RETRY,
    TASK_SUCCEEDED,
    TASK_FAILED,

    APPROVAL_REQUESTED,
    APPROVAL_GRANTED,
    APPROVAL_REJECTED,

    WORKFLOW_RESUMED,
    WORKFLOW_COMPLETED,
    WORKFLOW_ROLLED_BACK,

    POLICY_VALIDATION_STARTED,
    POLICY_VALIDATION_PASSED,
    POLICY_VIOLATION,

    WORKFLOW_SAFE_STOPPED,

    REPLANNING_STARTED,
    REPLANNING_COMPLETED,
    REPLANNING_FAILED,
    FALLBACK_EXECUTED
}